apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: account-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - rbac.poorops.com
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.poorops.com
  resources:
  - accounts/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.poorops.com
  resources:
  - accounts/status
  verbs:
  - get
  - patch
  - update
