# permissions for end users to edit accounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: account-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: account-operator
    app.kubernetes.io/part-of: account-operator
    app.kubernetes.io/managed-by: kustomize
  name: account-editor-role
rules:
- apiGroups:
  - rbac.poorops.com
  resources:
  - accounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.poorops.com
  resources:
  - accounts/status
  verbs:
  - get
