apiVersion: rbac.poorops.com/v1
kind: Account
metadata:
  labels:
    app.kubernetes.io/name: account
    app.kubernetes.io/instance: account-sample
    app.kubernetes.io/part-of: account-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: account-operator
  name: u1
spec:
  namespaces: ["test"]
  clusterRole: tmp
  #rules:
  #  - apiGroups: [""]
  #    resources: ["configmaps"]
  #    verbs: ["get", "watch", "list"]
